title: "DENDE"
author: "Idelfonso Nogueira"
description: "Idelfonso Nogueira – Chemical Engineering, Process Systems Engineering and AI Researcher"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home", icon: home}
  - {file: "Resume.md", title: "About us", icon: file}
  - {file: "research.md", title: "Research", icon: book-open}
  - {file: "orientations.md", title: "Supervision", icon: university}
  - {file: "teaching.md", title: "Teaching", icon: chalkboard-teacher}
  - {file: "people.md", title: "People", icon: users}
  - {file: "publications.md", title: "Publications", icon: atom}
  - {file: "collaborations.md", title: "Collaborations", icon: handshake}
  - {file: "project.md", title: "Projects", icon: link}
  - {file: "open.md", title: "Open Positions", icon: user-tie}
  - {file: "memories.md", title: "Memories", icon: image}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Software, icon: laptop-code, url: "https://www.ntnu.edu/employees/idelfonso.b.d.r.nogueira"}
  - {title: Mail, icon: envelope, url: "mailto:idelfonso.b.d.r.nogueira@ntnu.no"}
  
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
